$(document).ready(function(){
    $(".faqbox0").click(function(){
        $("#para0").slideToggle();
    });
});
$(document).ready(function(){
    $(".faqbox1").click(function(){
        $("#para1").slideToggle();
    });
});
$(document).ready(function(){
    $(".faqbox2").click(function(){
        $("#para2").slideToggle();
    });
});
$(document).ready(function(){
    $(".faqbox3").click(function(){
        $("#para3").slideToggle();
    });
});
$(document).ready(function(){
    $(".faqbox4").click(function(){
        $("#para4").slideToggle();
    });
});
$(document).ready(function(){
    $(".faqbox5").click(function(){
        $("#para5").slideToggle();
    });
});